### PR TITLE
Google Analytics Displayfeatures

### PR DESCRIPTION
**Pull request by DanielKulbe**
for issue #3

### CODE REVIEW

**Comment by bobdenotter** [comment]
We've refactored the extension, so this PR gives some big merge conflicts.. I'll probably be able to add this tweak to the new code, but I don't think I can merge in this PR.

**Comment by DanielKulbe** [comment]
For sure, changed this to bolt-2 target and will take a further look, to resolve the conflicts.

**Comment by DanielKulbe** [comment]
@bobdenotter ... just found a little time to update this PR.

**Comment by SahAssar** [comment]
Since we don't support 2.X anymore I suspect this won't get merged, if you can PR to the 3.X (master) branch that'd be awesome :)

**Pull request closed without merging**
